title: console-jkl
show_downloads: true
git_branch: master
logo_url:
google_analytics:
theme: 
custom_head: false
custom_sidebar: false
custom_footer: false
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
